### ISSUE TITLE
AMQ Interconnect Router repos cannot be added to IBMC VMs

### ISSUE THREAD

**Issue by rhkp** [RHEcosystemAppEng/amq-cob#10]
IBMC VM with RHEL8 minimal image throws this error..

Error: 'amq-interconnect-1-for-rhel-8-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Error: 'amq-clients-2-for-rhel-8-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.

**Comment by mpaulgreen** [comment]
@rhkp can you try these steps
```
subscription-manager remove --all
subscription-manager unregister
subscription-manager clean
mv /etc/rhsm/rhsm.conf /etc/rhsm/rhsm.conf.sat-backup
mv /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf
sudo subscription-manager register --username <your-acc>\ --password <your-password> --auto-attach
sudo subscription-manager repos --enable=interconnect-2-for-rhel-8-x86_64-rpms
sudo subscription-manager repos --enable=amq-clients-2-for-rhel-8-x86_64-rpms
sudo yum install qpid-dispatch-router qpid-dispatch-tools qpid-dispatch-console -y
which qdrouterd
```

**Comment by rhkp** [comment]
Thanks @mpaulgreen.

Validated the instructions and I am now able to install the AMQ Interconnect.
