### ISSUE TITLE
The UDP configuration is lost when the VM is shutdown

### ISSUE THREAD

**Issue by mpaulgreen** [RHEcosystemAppEng/amq-cob#3]
When I started the VM today which was preconfigured with UDP settings as mentioned in readme docs for HA - replication, it was lost. I had to reconfigure it.

**Comment by sgahlot** [comment]
@mpaulgreen what do you mean it was lost? Lost as the config was deleted or the cluster didn't go in HA replication mode anymore. I need some more info to recreate the issue.

**Comment by mpaulgreen** [comment]
@sgahlot - When I set up cluster, I used this command as described in readme.md 
sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev lo 

The cluster was set up.

I switched of my vm and restarted it over the weekend. The brokers were not part of the cluster. I had re-issue the above command to make the brokers participate in the cluster

**Comment by sgahlot** [comment]
Created PR to provide the info on making the route persistent. I couldn't find an easy way to do so (for loopback interface), hence I had to resort to creating a custom script for this.
PR: https://github.com/RHEcosystemAppEng/amq-cob/pull/4

**Comment by mpaulgreen** [comment]
@rhkp Can you execute this script on a RHEL VM and check whether 2 broker are joining in a cluster in UDP. Take the broker configuration from the files present in the repo. As discussed.

**Comment by rhkp** [comment]
Ok sure. Checking.

**Comment by rhkp** [comment]
Reproduced the issue in HA Replication setup and fix works fine for me.
