### ISSUE TITLE
Explore if two instances of interconnect router can be started on a single VM.

### ISSUE THREAD

**Issue by mpaulgreen** [RHEcosystemAppEng/amq-cob#5]

**Comment by rhkp** [comment]
Hi @mpaulgreen Are we still looking at this usecase when we are making use of the cloud throughout? If yes, I can begin looking at this one. Please advise/confirm.

Thanks,
Kamlesh.

**Comment by mpaulgreen** [comment]
This is no longer relevant as we are using the cloud environment.

**Comment by rhkp** [comment]
Thanks @mpaulgreen for confirming. Wish you a great day ahead.
