### ISSUE TITLE
Connection to 2nd broker fails from aggregator router

### ISSUE THREAD

**Issue by sgahlot** [RHEcosystemAppEng/amq-cob#7]
In the aggregator topology, the aggregator router fails to connect to the second broker with the following error message:
`Connection to amq-live-02:61616 failed: amqp:unauthorized-access Authentication failed [mech=none]`.

The configuration was based on the instructions given in https://github.com/RHEcosystemAppEng/amq-cob/tree/master/manualconfig/routertopology/aggregator except that _the live brokers were running on separate VMs_ with amq-live-01 being the hostname of the first live broker and amq-live-02 being the second live broker.

Here's some key config for the two brokers with their ports:
```# connectors for Brokers
connector {
    name: broker-connector-1
    host: amq-live-01
    port: 61616
    role: route-container
    saslMechanisms: ANONYMOUS
}

connector {
    name: broker-connector-2
    host: amq-live-02
    port: 61616
    role: route-container
    saslMechanisms: ANONOYMOUS
}```

**Comment by rhkp** [comment]
Solution is to add SASL PLAIN mechanism to the connector definition in router: qdrouterd.conf.

**Broker Config**

artemis-users.properties
Add the following line at the end
aggregate=redhat

artemis-roles.properties
Append aggregate user so the line looks as follows
amq = admin,aggregate

login.config
In this file be sure the line with org.apache.activemq.jaas.guest.user= looks as follows
 org.apache.activemq.jaas.guest.user="aggregate"


**Router Config**
Update connector definition to broker as follows in qdrouterd.conf file
connector {
    name: broker-connector-2
    host: 10.249.64.5
    port: 61617
    role: route-container
    saslMechanisms: PLAIN
    saslUsername: aggregate
    saslPassword: redhat
}

Start broker and router and ensure the error is not thrown.
