### ISSUE TITLE
File Storage - File Storage for VPC is available for customers with special approval to preview this service in the Washington, Dallas, Frankfurt, London, Paris, and Sydney regions. Contact your IBM Sales representative if you are interested in getting access." And this is only available above

### ISSUE THREAD

**Issue by mpaulgreen** [RHEcosystemAppEng/amq-cob#8]
[References - https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-vpc-abou](https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-vpc-about)

@rhkp - to move forward, try with create a nfs-server in a VM that acts as a storage and brokers as nfs-client.

**Comment by sgahlot** [comment]
We're using AWS instead of IBMC for all of our tests.
